artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: s3://elasticbeanstalk-us-east-1-263293423627/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data
  

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_dir: artifacts/prepare_base_model/base_model.h5
  update_base_model_dir: artifacts/prepare_base_model/base_model_updated.h5
  

training:
  root_dir: artifacts/training
  model_dir: artifacts/training/model.h5
  

