artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: s3://elasticbeanstalk-us-east-1-263293423627/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data
  